# -*- coding: utf-8 -*-
"""Lab 3: AI Architect/Practitioner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IuGTRuwzpGnqX66I85a6_Q94DsBN1xGF

# Modern AI Pro · AI Architect Practitioner · Lab 3

**Agentic RAG — when one retrieval pass *can't* be enough.** The agent **routes, decomposes, self-corrects, and reaches out to the web.** Corpus: a deliberately *shallow* ~136-doc Modern AI Pro catalog — so depth questions force the agent to do more than retrieve once.

**Lab 3 is eight moves — the corpus is shallow on purpose, so the agent must do more than retrieve once:**

0. **Setup** — load the ~136-doc Modern AI Pro catalog + golden set; wire the LLM + **Tavily** web search.
1. **Where single-shot breaks** — naive RAG on the golden set: site/topic answers fine, but **multi-hop** is incomplete, **depth** questions get declined/hallucinated, and *"what's 17×4"* wastes a retrieval.
2. **Query router** — classify each query: `direct` (no retrieval) · `retrieve` (in-corpus) · `decompose` (multi-hop).
3. **HyDE + multi-query** — bridge the query↔document vocabulary gap and widen recall.
4. **Decomposition** — split a multi-hop question into sub-queries, retrieve each, synthesize.
5. **Sufficiency loop + CRAG + web fallback** — score whether retrieval is *enough*; if not, search the web (Tavily) and synthesize catalog + web with citations. **The star move.**
6. **Budget caps** — `maxLlmCalls` + wall-clock, so the agent can't loop forever.
7. **Re-score** — agentic vs naive on the golden set: answer correctness **+ cost**. Agentic wins because it routes, decomposes, and reaches the web.

> The recipe that wins: **when your corpus can't answer, the agent reasons and reaches out — instead of confidently making something up.**

## Move 0 · Setup — catalog corpus + LLM + Tavily web search
"""

# --- repo local-run shim (added when these labs were moved out of Colab) ----
# Runs in VS Code / plain `python` as well as Colab:
#   * install ONCE in your venv (not per cell):  pip install "mai_rag[evals,viz]"
#   * put your key in a .env file at the repo root:  GROQ_API_KEY=gsk_...
#   * userdata.get(KEY) reads that .env (or any env var) when off-Colab
#   * display(...) falls back to print() outside a notebook
import os, pathlib

# Load .env (KEY=VALUE lines) from the repo root / cwd into the environment.
# Structural parse of a config file — no extra dependency needed.
for _cand in (pathlib.Path(".env"),
              pathlib.Path(__file__).resolve().parent.parent / ".env",
              pathlib.Path(__file__).resolve().parent / ".env"):
    if _cand.exists():
        for _line in _cand.read_text().splitlines():
            _line = _line.strip()
            if _line and not _line.startswith("#") and "=" in _line:
                _k, _v = _line.split("=", 1)
                os.environ.setdefault(_k.strip(), _v.strip().strip('"').strip("'"))
        break

try:
    from google.colab import userdata  # type: ignore
except Exception:
    class _UD:
        @staticmethod
        def get(k): return os.environ.get(k)
    userdata = _UD()
try:
    display  # type: ignore  (provided by Jupyter / VS Code interactive)
except NameError:
    def display(*a, **k):
        for x in a: print(x)
# ---------------------------------------------------------------------------


# [pip/install handled once in your venv — see CLAUDE.md] !pip install -q -U "mai_rag[evals] @ git+https://github.com/balajivis/ai-architect-labs.git"
# [pip/install handled once in your venv — see CLAUDE.md] !pip install -q -U langchain_groq tavily-python

import mai_rag, pandas as pd, numpy as np, json
print("mai_rag", mai_rag.__version__)   # need >= 0.1.5 for load_catalog_corpus

from mai_rag import corpus
# from google.colab import userdata   # (replaced by repo shim above)
from langchain_groq import ChatGroq
from tavily import TavilyClient

store  = corpus.load_catalog_corpus(rebuild=True)    # ~136 shallow catalog docs, embeds live ~20s
golden = corpus.load_golden_catalog()                # 12 cases, tagged for the agentic moves
print(store.stats())
print(len(golden), "golden cases:", {t: sum(c["tag"] == t for c in golden) for t in {c["tag"] for c in golden}})

llm    = ChatGroq(model_name="openai/gpt-oss-120b", api_key=userdata.get("GROQ_API_KEY"), temperature=0)
tavily = TavilyClient(api_key=userdata.get("TAVILY_API_SEARCH"))
def _json(raw):                                      # LLMs wrap JSON in prose — slice it out
    return json.loads(raw[raw.find("{"): raw.rfind("}") + 1])
print("LLM + Tavily ready")

"""## Move 1 · Where single-shot RAG breaks

Run naive RAG over the golden set and watch it stumble exactly where the catalog is shallow or the query is the wrong shape: **multi-hop** answers come back half-complete, **depth** (`needs-web`) questions get declined or confidently invented, and **no-retrieval** questions (*"what's 17×4"*) waste a retrieval on documents that can't help. These are the failures the agent will fix.
"""

def search(q, k=5):
    return store.search(q, k=k)

def naive_rag(q, k=5):
    hits = search(q, k)
    ctx = "\n\n".join(f"[{i+1}] ({h.source}) {h.content}" for i, h in enumerate(hits))
    p = ("Answer using ONLY the context. If it isn't there, say you don't have enough information.\n\n"
         f"Question: {q}\n\nContext:\n{ctx}\n\nAnswer:")
    return llm.invoke(p).content

# watch single-shot stumble on the hard-shaped queries
for c in golden:
    if c["tag"] in ("multi-hop", "needs-web", "no-retrieval"):
        print(f"[{c['tag']}] {c['q']}")
        print("   ->", naive_rag(c["q"])[:170].replace("\n", " "), "\n")

"""## Move 2 · Query router — not every query needs retrieval

The first agentic decision: *should we retrieve at all, and how?* An LLM classifies the query and we route it — `direct` (greetings, math, general knowledge → just answer), `retrieve` (a normal in-corpus question), or `decompose` (a comparison / multi-part question that needs more than one retrieval). This alone fixes the wasted-retrieval failures.
"""

def analyze_query(q):
    p = ('Classify this query. Reply JSON only: '
         '{"needs_retrieval": true|false, "type": "factual|comparison|conversational|math", '
         '"complexity": "simple|complex", "reason": "<short>"}. '
         'needs_retrieval=false for greetings, chit-chat, and pure math / general knowledge that needs no documents.\n\n'
         f'Query: {q}')
    return _json(llm.invoke(p).content)

def route(q):
    a = analyze_query(q)
    if not a["needs_retrieval"]:                                   return "direct"
    if a["type"] == "comparison" or a["complexity"] == "complex":  return "decompose"
    return "retrieve"

for c in golden:
    print(f"{route(c['q']):10s} <- [{c['tag']:12s}] {c['q'][:58]}")

"""## Move 3 · HyDE + multi-query — bridge the vocabulary gap

A user's words rarely match the document's words. **HyDE** drafts a hypothetical answer and retrieves with *that* (answer-to-answer matching); **multi-query** rewrites the question several ways and pools the hits. Both widen recall before the agent commits.
"""

def hyde(q):
    return llm.invoke(f"Write a 2-sentence hypothetical answer to this question:\n{q}\nAnswer:").content

def multi_query(q, n=3):
    out = llm.invoke(f"Write {n} alternative search queries for this question, one per line:\n{q}").content
    return [l.strip(" -*0123456789.") for l in out.splitlines() if l.strip()][:n]

def hyde_search(q, k=5):
    return store.search(f"{q}\n{hyde(q)}", k=k)

q = "How does an agent decide what action to take at each step?"
print("naive retrieval :", [h.source for h in search(q, 3)])
print("HyDE  retrieval :", [h.source for h in hyde_search(q, 3)])
print("\nmulti-query expansions:", multi_query(q))

"""## Move 4 · Decomposition — multi-hop needs more than one retrieval

A question like *"how does the Practitioner course differ from Vibe Coding?"* needs facts from **two** documents — one retrieval can't get both. So the agent splits it into standalone sub-questions, retrieves each, unions the context, and synthesizes. This fixes the multi-hop failures from Move 1.
"""

def decompose(q):
    out = llm.invoke(f"Break this into 2-3 standalone sub-questions, one per line:\n{q}").content
    return [l.strip(" -*0123456789.") for l in out.splitlines() if "?" in l][:3]

def agentic_retrieve(q, k=4):
    subs = decompose(q)
    docs, seen = [], set()
    for s in subs:
        for h in store.search(s, k=k):
            if h.source not in seen:
                seen.add(h.source); docs.append((h.source, h.content))
    return subs, docs

def decomposed_answer(q):
    subs, docs = agentic_retrieve(q)
    ctx = "\n\n".join(f"[{s}] {c}" for s, c in docs)
    ans = llm.invoke(f"Using this context, answer with inline [source] citations: {q}\n\nContext:\n{ctx}\n\nAnswer:").content
    return subs, ans

q = next(c["q"] for c in golden if c["tag"] == "multi-hop")
subs, ans = decomposed_answer(q)
print("Q:", q, "\n\nsub-questions:", subs, "\n\nANSWER:\n", ans[:400])

"""## Move 5 · Sufficiency loop + Corrective RAG + web fallback ⭐

The catalog is shallow — so for depth questions (an exact formula, a benchmark number) retrieval *looks* relevant but isn't *enough*. The agent **judges sufficiency**; if the context falls short, it **corrects course and searches the web (Tavily)**, then synthesizes catalog + web with citations. This turns *"I don't have that"* — or a confident hallucination — into a real, sourced answer. **The recipe that wins.**
"""

def sufficient(q, docs):
    ctx = "\n".join(c for _, c in docs)[:2500]
    p = ('Can the CONTEXT answer the QUESTION specifically and completely (exact facts, not just the topic)? '
         'Reply JSON only: {"sufficient": true|false, "why": "<short>"}.\n\n'
         f'QUESTION: {q}\nCONTEXT: {ctx}')
    return _json(llm.invoke(p).content)["sufficient"]

def web_search(q, k=3):
    r = tavily.search(query=q, max_results=k)
    return [(x["url"], x["content"]) for x in r["results"]]

def crag_answer(q, k=4):
    hits = [(h.source, h.content) for h in store.search(q, k=k)]
    source = "catalog"
    if not sufficient(q, hits):                       # the corrective step
        hits = hits[:2] + web_search(q)
        source = "catalog + WEB"
    ctx = "\n\n".join(f"[{s}] {c}" for s, c in hits)
    ans = llm.invoke(f"Answer using ONLY the context; cite sources inline as [source].\n\nQ: {q}\n\nContext:\n{ctx}\n\nAnswer:").content
    return source, ans

q = next(c["q"] for c in golden if c["tag"] == "needs-web")
source, ans = crag_answer(q)
print(f"Q: {q}\n\nSOURCE USED: {source}\n\n{ans[:500]}")

"""## Move 6 · Budget caps — the agent that can't run forever

Agentic loops must be bounded or they explode cost and latency. We wrap the whole pipeline — **route → (direct | retrieve+CRAG | decompose+CRAG)** — in a budget that caps LLM calls and wall-clock time and fails gracefully. This `agent()` is the finished product: one entry point that routes, decomposes, self-corrects, and reaches the web.
"""

import time

class Budget:
    def __init__(self, max_calls=10, max_seconds=40):
        self.max_calls, self.max_seconds, self.calls, self.t0 = max_calls, max_seconds, 0, time.time()
    def tick(self):
        self.calls += 1
        if self.calls > self.max_calls:               raise RuntimeError("budget: too many LLM calls")
        if time.time() - self.t0 > self.max_seconds:  raise RuntimeError("budget: wall-clock exceeded")

def agent(q):
    b = Budget(); strat = route(q); b.tick()
    if strat == "direct":
        return "direct", llm.invoke(f"Answer this briefly and directly: {q}").content
    if strat == "decompose":
        _, docs = agentic_retrieve(q); b.tick()
    else:
        docs = [(h.source, h.content) for h in store.search(q, k=4)]
    used = "catalog"
    if not sufficient(q, docs):                       # CRAG corrective step on either retrieval path
        docs = docs[:2] + web_search(q); used = "catalog + WEB"; b.tick()
    ctx = "\n\n".join(f"[{s}] {c}" for s, c in docs)
    ans = llm.invoke(f"Answer using ONLY the context; cite sources inline as [source].\n\nQ: {q}\n\nContext:\n{ctx}\n\nAnswer:").content
    return f"{strat}/{used}", ans

for c in golden[:5]:
    s, a = agent(c["q"]); print(f"[{s}]  {c['q'][:54]}\n   -> {a[:130]}\n")

"""## Move 7 · Re-score — agentic vs naive (correctness + cost)

The finale: grade the full `agent()` against naive RAG on the same golden set. The agent should win across the board — it answers no-retrieval questions **directly**, completes **multi-hop** with decomposition, and rescues **depth** questions with the web — while the route column reminds you agentic isn't free (more LLM calls, web latency), which is exactly what motivates routing: **only pay for agentic when the query needs it.**
"""

def grade(q, ans, expected):
    p = ('Grade the ANSWER against EXPECTED: 1.0 fully correct, 0.5 partial, 0.0 wrong/missing. '
         'If EXPECTED says no-retrieval/direct, reward a correct direct answer; if it says needs-web, '
         'reward a correct sourced answer. JSON only: {"score": <1.0|0.5|0.0>}.\n\n'
         f'Q: {q}\nEXPECTED: {expected}\nANSWER: {ans}')
    return _json(llm.invoke(p).content)["score"]

rows = []
for c in golden:
    n = naive_rag(c["q"])
    route_used, a = agent(c["q"])
    rows.append({"tag": c["tag"], "route": route_used,
                 "naive": grade(c["q"], n, c["expected"]),
                 "agentic": grade(c["q"], a, c["expected"])})

df = pd.DataFrame(rows)
pd.set_option("display.max_colwidth", 32)
display(df)
print("\nMEANS:", df[["naive", "agentic"]].mean().round(3).to_dict())
print("Agentic wins by ROUTING (skips needless retrieval), DECOMPOSING (multi-hop), and reaching the WEB (depth).")