# -*- coding: utf-8 -*-
"""Lab 4: AI Architect/Practitioner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ziMG9QO4fj5kgzCNaFAsFG1kaxSWJ5_k

# Modern AI Pro · AI Architect Practitioner · Lab 4

**Memory & Personalization — retrieval that compounds.** Labs 1–3 treat every query as independent. Here the agent **remembers who you are and what you asked** — so follow-ups resolve and answers personalize. Stateless RAG literally *can't* do this; memory is the clearest win of the four labs.

**Lab 4 is eight moves — each fixes a failure that only appears across a *conversation*:**

0. **Setup** — catalog corpus + LLM + **golden conversations** (multi-turn dialogues where later turns depend on earlier ones).
1. **Where stateless breaks** — answer each turn independently → follow-ups collapse (*"is there a course for that?"* → *"for what?"*).
2. **Working + short-term memory** — a rolling window + rewrite the follow-up into a standalone query → follow-ups resolve.
3. **Token-efficient memory** — summarize old turns, keep a recent window → multi-turn stays cheap.
4. **Long-term user memory** — extract durable user facts into a profile → personalized answers.
5. **User-scoped retrieval** — bias retrieval by the profile (a PM gets PM docs first).
6. **Decay & observability** — inspect and prune what the agent remembers; memory that doesn't rot.
7. **Re-score** — conversations **with vs without** memory: follow-up resolution + personalization. Memory clearly wins.

> The recipe that wins: **remember the user, and retrieval compounds turn over turn** — the thing stateless RAG simply can't do.

## Move 0 · Setup — catalog corpus + golden conversations
"""

# --- repo local-run shim (added when these labs were moved out of Colab) ----
# Runs in VS Code / plain `python` as well as Colab:
#   * install ONCE in your venv (not per cell):  pip install "mai_rag[evals,viz]"
#   * put your key in a .env file at the repo root:  GROQ_API_KEY=gsk_...
#   * userdata.get(KEY) reads that .env (or any env var) when off-Colab
#   * display(...) falls back to print() outside a notebook
import os, pathlib

# Load .env (KEY=VALUE lines) from the repo root / cwd into the environment.
# Structural parse of a config file — no extra dependency needed.
for _cand in (pathlib.Path(".env"),
              pathlib.Path(__file__).resolve().parent.parent / ".env",
              pathlib.Path(__file__).resolve().parent / ".env"):
    if _cand.exists():
        for _line in _cand.read_text().splitlines():
            _line = _line.strip()
            if _line and not _line.startswith("#") and "=" in _line:
                _k, _v = _line.split("=", 1)
                os.environ.setdefault(_k.strip(), _v.strip().strip('"').strip("'"))
        break

try:
    from google.colab import userdata  # type: ignore
except Exception:
    class _UD:
        @staticmethod
        def get(k): return os.environ.get(k)
    userdata = _UD()
try:
    display  # type: ignore  (provided by Jupyter / VS Code interactive)
except NameError:
    def display(*a, **k):
        for x in a: print(x)
# ---------------------------------------------------------------------------


# [pip/install handled once in your venv — see CLAUDE.md] !pip install -q -U "mai_rag[evals] @ git+https://github.com/balajivis/ai-architect-labs.git"
# [pip/install handled once in your venv — see CLAUDE.md] !pip install -q -U langchain_groq

import mai_rag, pandas as pd, json
print("mai_rag", mai_rag.__version__)   # need >= 0.1.5

from mai_rag import corpus
# from google.colab import userdata   # (replaced by repo shim above)
from langchain_groq import ChatGroq

store = corpus.load_catalog_corpus(rebuild=True)     # same ~136-doc MAI catalog as Lab 3
llm   = ChatGroq(model_name="openai/gpt-oss-120b", api_key=userdata.get("GROQ_API_KEY"), temperature=0)
def _json(raw): return json.loads(raw[raw.find("{"): raw.rfind("}") + 1])
def retrieve(q, k=4):
    return "\n\n".join(f"[{h.source}] {h.content}" for h in store.search(q, k=k))

# Golden CONVERSATIONS — later turns DEPEND on earlier ones (follow-ups + personalization).
# `needs_memory=True` marks the turns a stateless bot cannot answer.
conversations = [
    {"persona": "PM, non-coder, new to AI",
     "turns": [
        {"user": "I'm a product manager, new to AI, and I don't code.",
         "expect": "Acknowledge the user's context.", "needs_memory": False},
        {"user": "What should I focus on learning first?",
         "expect": "PM-relevant AI skills (prompting, AI-assisted PRDs, evals for product) — tailored to a non-coding PM.", "needs_memory": True},
        {"user": "Is there a course for that?",
         "expect": "AI for PMs — a 1-day course for product managers.", "needs_memory": True},
        {"user": "How long is it and who is it for?",
         "expect": "1 day, for product managers.", "needs_memory": True},
     ]},
    {"persona": "Senior engineer, Python, wants production RAG",
     "turns": [
        {"user": "I'm a senior backend engineer, very comfortable with Python.",
         "expect": "Acknowledge the user's context.", "needs_memory": False},
        {"user": "I want to build production RAG systems — which course should I take?",
         "expect": "AI Practitioner / AI Architect (RAG, evals, MCP, trust).", "needs_memory": True},
        {"user": "How is it different from the vibe coding one?",
         "expect": "Practitioner builds AI systems; Vibe Coding is AI-assisted coding.", "needs_memory": True},
        {"user": "Will it cover evaluations?",
         "expect": "Yes — evaluations are a core layer of the Practitioner course.", "needs_memory": True},
     ]},
]
print(len(conversations), "conversations,", sum(len(c["turns"]) for c in conversations), "turns",
      "|", sum(t["needs_memory"] for c in conversations for t in c["turns"]), "memory-dependent")

"""## Move 1 · Where stateless RAG breaks

Answer each turn on its own — no memory of prior turns. The opening turn works, but the moment the user says *"is there a course for **that**?"* or *"how long is **it**?"*, the bot has no idea what *that* / *it* refers to. Follow-ups — the heart of any real conversation — collapse.
"""

def stateless_answer(user_msg):
    ctx = retrieve(user_msg)
    return llm.invoke(f"Answer the user using the catalog context.\n\nUser: {user_msg}\n\nContext:\n{ctx}\n\nAnswer:").content

# replay conversation 1 with NO memory — watch the follow-ups fall apart
for t in conversations[0]["turns"]:
    print("USER:", t["user"])
    print("BOT :", stateless_answer(t["user"])[:150].replace("\n", " "), "\n")

"""## Move 2 · Working + short-term memory — resolve the follow-up

Keep a rolling window of recent turns, and **before retrieving, rewrite the follow-up into a standalone question** using that history (*"is there a course for that?"* → *"is there a course on AI for product managers?"*). Now retrieval finds the right doc and the bot stays coherent. The query-rewrite is the trick — retrieval can't follow a pronoun, but a rewrite can.
"""

class ShortTermMemory:
    def __init__(self, window=6):
        self.turns, self.window = [], window
    def add(self, role, text): self.turns.append((role, text))
    def context(self): return "\n".join(f"{r}: {t}" for r, t in self.turns[-self.window:])

def chat(user_msg, mem):
    history = mem.context()
    standalone = llm.invoke("Given the conversation, rewrite the user's LAST message as a standalone question "
                            f"(resolve any pronouns like 'that'/'it').\n\n{history}\nUser: {user_msg}\n\nStandalone question:").content
    ctx = retrieve(standalone)
    ans = llm.invoke(f"Conversation so far:\n{history}\n\nUser: {user_msg}\n\nCatalog context:\n{ctx}\n\nAnswer:").content
    mem.add("User", user_msg); mem.add("Bot", ans)
    return ans, standalone

mem = ShortTermMemory()
for t in conversations[0]["turns"]:
    ans, standalone = chat(t["user"], mem)
    print("USER:", t["user"])
    print("  rewritten ->", standalone[:80])
    print("BOT :", ans[:150].replace("\n", " "), "\n")

"""## Move 3 · Token-efficient memory — don't pay for the whole history

A growing window means every turn re-sends the *entire* conversation — cost climbs turn over turn. Instead, **compact** the oldest turns into a running summary and keep only a short recent window: constant-size context, full continuity. This is the difference between a chatbot that's cheap at turn 50 and one that isn't.
"""

class CompactingMemory(ShortTermMemory):
    def __init__(self, window=4):
        super().__init__(window=window); self.summary = ""
    def add(self, role, text):
        super().add(role, text)
        if len(self.turns) > self.window * 2:                  # fold oldest turns into a running summary
            old = self.turns[:-self.window]
            self.summary = llm.invoke("Update the running summary with these older turns (<=60 words).\n"
                                      f"Summary: {self.summary}\nTurns:\n" +
                                      "\n".join(f"{r}: {t}" for r, t in old)).content
            self.turns = self.turns[-self.window:]
    def context(self):
        head = f"[summary] {self.summary}\n" if self.summary else ""
        return head + "\n".join(f"{r}: {t}" for r, t in self.turns[-self.window:])

mem = CompactingMemory(window=2)
for c in conversations:
    for t in c["turns"]:
        chat(t["user"], mem)
print(f"after {sum(len(c['turns']) for c in conversations)} turns, the context stays bounded:\n")
print(mem.context())

"""## Move 4 · Long-term user memory — personalization

Some facts outlive the conversation: *who the user is, what they know, what they want.* Extract those **durable** facts into a profile and inject it into every answer. Now *"what should I learn first?"* gets an answer tailored to **this** user (a non-coding PM) instead of a generic one — the same question, a different answer per person.
"""

class UserProfile:
    def __init__(self): self.facts = []
    def update(self, user_msg):
        out = llm.invoke('Extract DURABLE facts about the user (role, skills, goals) from this message. '
                         'Reply JSON only: {"facts": ["..."]} (empty list if none).\n\n'
                         f'Message: "{user_msg}"').content
        for f in _json(out).get("facts", []):
            if f not in self.facts: self.facts.append(f)
    def text(self): return "; ".join(self.facts) or "(unknown user)"

profile = UserProfile()
for t in conversations[0]["turns"]:
    profile.update(t["user"])
print("Learned profile:", profile.text(), "\n")

q = "What should I focus on learning first?"
generic  = llm.invoke(f"Q: {q}\nContext:\n{retrieve(q)}\n\nAnswer:").content
personal = llm.invoke(f"User profile: {profile.text()}\n\nQ: {q}\nContext:\n{retrieve(q)}\n\n"
                      "Give a recommendation tailored to THIS user:").content
print("GENERIC :", generic[:160].replace("\n", " "))
print("\nPERSONAL:", personal[:240].replace("\n", " "))

"""## Move 5 · User-scoped retrieval — personalization at retrieval time

Personalization isn't only in the *answer* — it changes **what you retrieve**. Fold the user profile into the query so the right docs surface first: a non-coding PM and a senior engineer asking the *same* question should get *different* documents.
"""

def scoped_search(q, profile, k=3):
    return [h.source for h in store.search(f"{q} (for: {profile.text()})", k=k)]

q = "which course should I take?"
pm  = UserProfile(); pm.facts  = ["product manager", "does not code", "new to AI"]
eng = UserProfile(); eng.facts = ["senior backend engineer", "knows Python", "wants production RAG"]

print("generic    :", [h.source for h in store.search(q, 3)])
print("PM-scoped  :", scoped_search(q, pm))
print("eng-scoped :", scoped_search(q, eng))
print("\nSame question, different retrieved docs -> personalization happens at retrieval, not just generation.")

"""## Move 6 · Decay & observability — memory that doesn't rot

Memory you can't inspect is memory you can't trust. Print what the agent holds — the recent window, the running summary, the user profile — and apply simple **decay** (cap the profile, drop the oldest facts) so it stays current instead of accumulating forever.
"""

# observability: see exactly what the agent remembers
print("=== short-term window ===\n", mem.context())
print("\n=== running summary ===\n", getattr(mem, "summary", "(none)") or "(none)")
print("\n=== long-term profile ===\n", profile.text())

# decay: keep only the most recent N durable facts so the profile stays current
def decay(profile, keep=5):
    profile.facts = profile.facts[-keep:]
    return profile.text()
print("\n=== profile after decay (keep 5) ===\n", decay(profile, keep=5))

"""## Move 7 · Re-score — with vs without memory

Replay the golden conversations two ways — stateless, and with the memory agent — and grade only the **memory-dependent** turns (the follow-ups and personalized asks). Stateless should crater on exactly those turns; the memory agent should resolve them. That gap is the whole lab — and unlike retrieval tricks, it's a win that *can't* be argued away, because stateless RAG simply cannot carry context.
"""

def grade_turn(user, answer, expect):
    p = ('Did the ANSWER correctly handle the user turn, given EXPECTED? 1.0 yes, 0.5 partial, 0.0 confused/wrong. '
         'JSON only: {"score": <1.0|0.5|0.0>}.\n\n'
         f'USER: {user}\nEXPECTED: {expect}\nANSWER: {answer}')
    return _json(llm.invoke(p).content)["score"]

rows = []
for conv in conversations:
    mem = ShortTermMemory()                              # fresh memory per conversation
    for t in conv["turns"]:
        s_ans = stateless_answer(t["user"])
        m_ans, _ = chat(t["user"], mem)
        if t["needs_memory"]:
            rows.append({"turn": t["user"][:42],
                         "stateless": grade_turn(t["user"], s_ans, t["expect"]),
                         "with_memory": grade_turn(t["user"], m_ans, t["expect"])})

df = pd.DataFrame(rows)
pd.set_option("display.max_colwidth", 44)
display(df)
print("\nMEANS:", df[["stateless", "with_memory"]].mean().round(3).to_dict())
print("Memory wins on exactly the turns that DEPEND on context — follow-ups and personalization.")