# -*- coding: utf-8 -*-
"""Lab 1: AI Architect/Practitioner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9Q8jOD3NktuuoUjYaW97woBoOGLRfor

# Modern AI Pro AI Architect Practitioner Lab 1

Goal: Build Evals and Golden test cases with a naive RAG application

**Lab 1 is five moves — all in Python this lab (no Node.js yet):**

1. **Explore** the corpus & embeddings — *cells 1–4*
2. **Set up the LLM** and **build a basic naive RAG** — *cells 5–6*
3. **Write golden test cases** (the core skill) — *cell 7*
4. **Build the evals** — LLM-as-judge (correctness) + 1 RAG metric (faithfulness) — *cell 8*
5. **Score the naive RAG** → read the per-case table; this baseline is the number every later lab must beat — *cell 9*
"""

# --- repo local-run shim (added when these labs were moved out of Colab) ----
# Runs in VS Code / plain `python` as well as Colab:
#   * install ONCE in your venv (not per cell):  pip install "mai_rag[evals,viz]"
#   * put your key in a .env file at the repo root:  GROQ_API_KEY=gsk_...
#   * userdata.get(KEY) reads that .env (or any env var) when off-Colab
#   * display(...) falls back to print() outside a notebook
import os, pathlib

# Load .env (KEY=VALUE lines) from the repo root / cwd into the environment.
# Structural parse of a config file — no extra dependency needed.
for _cand in (pathlib.Path(".env"),
              pathlib.Path(__file__).resolve().parent.parent / ".env",
              pathlib.Path(__file__).resolve().parent / ".env"):
    if _cand.exists():
        for _line in _cand.read_text().splitlines():
            _line = _line.strip()
            if _line and not _line.startswith("#") and "=" in _line:
                _k, _v = _line.split("=", 1)
                os.environ.setdefault(_k.strip(), _v.strip().strip('"').strip("'"))
        break

try:
    from google.colab import userdata  # type: ignore
except Exception:
    class _UD:
        @staticmethod
        def get(k): return os.environ.get(k)
    userdata = _UD()
try:
    display  # type: ignore  (provided by Jupyter / VS Code interactive)
except NameError:
    def display(*a, **k):
        for x in a: print(x)
# ---------------------------------------------------------------------------


# [pip/install handled once in your venv — see CLAUDE.md] !pip install -q -U "mai_rag[evals] @ git+https://github.com/balajivis/ai-architect-labs.git"

import mai_rag
print("mai_rag", mai_rag.__version__)

from mai_rag import corpus, evals, viz

store = corpus.load_policy_corpus("policy.db")   # copies the pre-embedded DB — instant (pass rebuild=True to embed from raw docs)
store.stats()

import pandas as pd, numpy as np
from mai_rag.store import embed

# 1 — how big is it?  (documents, chunks, golden_cases, eval_runs, eval_results)
store.stats()

# 2 — browse the corpus like data
docs = pd.read_sql("SELECT id, title, source, metadata FROM documents", store.conn)
docs.head(10);  docs.shape
docs["source"].str.split("-").str[0].value_counts()      # docs per department (adjust to source fmt)

# 3 — chunk granularity: what is retrieval actually fetching?
chunks = pd.read_sql("SELECT token_count, length(content) AS chars FROM chunks", store.conn)
chunks["token_count"].describe()
chunks["token_count"].hist(bins=40)

# 4 — see retrieval in action
for h in store.search("How much parental leave do I get?", k=5):
    print(f"{h.score:.3f}  {h.title}\n     {h.content[:120]}…")

# 5 - Setup LLM
# [pip/install handled once in your venv — see CLAUDE.md] !pip install -q -U langchain_groq
from langchain_groq import ChatGroq
# from google.colab import userdata   # (replaced by repo shim above)

llm_groq = ChatGroq(model_name="openai/gpt-oss-120b", api_key=userdata.get("GROQ_API_KEY"))

# 6 — Build a basic naive RAG: retrieve → stuff context → answer
def naive_rag(query, k=5):
    hits = store.search(query, k=k)
    context = "\n\n".join(f"[{i+1}] ({h.title}) {h.content}" for i, h in enumerate(hits))
    prompt = (
        "Answer the question using ONLY the context below. "
        "If the answer isn't there, say you don't have enough information.\n\n"
        f"Question: {query}\n\nContext:\n{context}\n\nAnswer:"
    )
    answer = llm_groq.invoke(prompt).content
    return {"answer": answer, "contexts": [h.content for h in hits]}

naive_rag("How much parental leave do I get?")["answer"]

# 7 — Golden test cases: HARD + grounded in the real docs (each has the supporting doc)
# Designed to break naive single-shot RAG: recency conflicts (active vs -legacy/superseded),
# multi-hop (answer spans 2 docs), precise thresholds, and an unanswerable (must decline, not invent).
golden = [
    # --- recency conflicts: the -legacy/superseded twin is a distractor naive RAG often surfaces ---
    {"q": "How many weeks of paid parental leave do primary caregivers get?",
     "expected": "16 weeks at 100% salary (effective May 1, 2026 — up from the superseded 8-week policy).",
     "support": "hr-parental-leave-active", "tag": "recency"},
    {"q": "How often must employees rotate their account passwords?",
     "expected": "There is no forced periodic rotation — the current NIST-aligned IAM policy removed the legacy 90-day rotation rule.",
     "support": "identity-access-management-policy", "tag": "recency"},
    {"q": "Can I use SMS text codes as my MFA method for VPN access?",
     "expected": "No. SMS is not permitted under the current VPN Client Standard (it was allowed only under the superseded legacy policy).",
     "support": "itsec-vpn-client-standard", "tag": "recency"},
    {"q": "Is the Juniper Pulse VPN client still supported?",
     "expected": "No — Juniper Pulse is deprecated; migrate to Cisco AnyConnect (5.1+) or OpenVPN (2.6+).",
     "support": "itsec-vpn-client-standard", "tag": "recency"},

    # --- multi-hop: answer needs facts from more than one place / row ---
    {"q": "Malware is detected on an employee laptop — what incident severity is it, and how fast must it be escalated?",
     "expected": "Sev-2 (High): report to the Security Team immediately, with exec team + affected customers notified within 2 hours.",
     "support": "incident-response-runbook", "tag": "multi-hop"},
    {"q": "I want to buy a $60,000 tool from a single vendor — what bidding is required AND who must approve the spend?",
     "expected": "$25K–$99,999 requires 3 competitive quotes (a sole-vendor waiver needs VP Procurement approval); the purchase itself must be approved by CFO + VP Procurement.",
     "support": "fin-procurement-thresholds-competitive-bidding + fin-purchase-approval-matrix", "tag": "multi-hop"},

    # --- precise threshold: the right row, not a neighbouring one ---
    {"q": "For a $30,000 purchase, how many competitive quotes are required?",
     "expected": "Three quotes (the $25,000–$99,999 band).",
     "support": "fin-procurement-thresholds-competitive-bidding", "tag": "precision"},
    {"q": "If both partners work at Northwind, how much parental leave does each receive?",
     "expected": "Each receives 16 weeks independently; the leave may overlap or be staggered.",
     "support": "hr-parental-leave-active", "tag": "precision"},

    # --- VPN config detail (current policy, not legacy) ---
    {"q": "Is split tunneling allowed on the corporate VPN?",
     "expected": "No — full-tunnel is mandatory (no split tunneling) effective May 1, 2026.",
     "support": "itsec-vpn-client-standard", "tag": "recency"},

    # --- unanswerable: the corpus has the revenue *method*, never the figure → must decline, not invent ---
    {"q": "What was Northwind's total revenue in fiscal year 2025?",
     "expected": "Not stated in the corpus — the documents define the revenue-recognition method, not the actual figure. The model should say it doesn't have enough information.",
     "support": "(none — should decline)", "tag": "unanswerable"},
]

print(len(golden), "cases:", {t: sum(c["tag"] == t for c in golden) for t in {c["tag"] for c in golden}})
golden[0]

# 8 — Build a basic eval: LLM-as-judge (correctness) + 1 RAG metric (faithfulness)
import json
judge = ChatGroq(model_name="openai/gpt-oss-120b", api_key=userdata.get("GROQ_API_KEY"),
                 temperature=0)  # deterministic grading

def _json(raw):                       # LLMs wrap JSON in prose — slice it out
    return json.loads(raw[raw.find("{"): raw.rfind("}") + 1])

def llm_judge(q, answer, expected):   # does the answer match what we expect?
    p = (f'Grade the ANSWER against EXPECTED for the QUESTION. '
         f'Reply JSON only: {{"score": <0..1>, "reason": "<short>"}}.\n\n'
         f'QUESTION: {q}\nEXPECTED: {expected}\nANSWER: {answer}')
    return _json(judge.invoke(p).content)

def faithfulness(answer, contexts):   # is every claim grounded in the retrieved context?
    ctx = "\n\n".join(contexts)
    p = (f'Is every claim in the ANSWER supported by the CONTEXT? '
         f'Reply JSON only: {{"score": <0..1>, "reason": "<short>"}} (1=grounded, 0=hallucinated).\n\n'
         f'CONTEXT:\n{ctx}\n\nANSWER: {answer}')
    return _json(judge.invoke(p).content)

out = naive_rag("How much parental leave do I get?")
print("CORRECTNESS:", llm_judge(golden[0]["q"], out["answer"], golden[0]["expected"]))
print("FAITHFULNESS:", faithfulness(out["answer"], out["contexts"]))

# 9 — Score the naive RAG across the golden set → the baseline to beat
import pandas as pd
rows = []
for c in golden:
    out = naive_rag(c["q"])
    rows.append({
        "question": c["q"][:45],
        "correctness": llm_judge(c["q"], out["answer"], c["expected"])["score"],
        "faithfulness": faithfulness(out["answer"], out["contexts"])["score"],
    })
df = pd.DataFrame(rows)
display(df)                                   # per-case — find the catastrophic low one
print("\nBASELINE:", df.mean(numeric_only=True).round(3).to_dict())   # the number every later lab must beat

"""## The home-rolled judge *is* the lesson — now make it sturdier

That baseline isn't trustworthy, and noticing **why** is the real skill:

- **Holistic faithfulness** — one "0–1, is it grounded?" call rubber-stamps ~1.0. A real metric **breaks the answer into claims and checks each** against the context.
- **No rubric, no reasoning** — round, arbitrary scores you can't audit (row 7 scored 0/0 with no explanation).
- **Not deterministic** — Groq varies even at `temperature=0`, so two runs disagree.

Below: the same model, but a **claim-based faithfulness**, an **anchored rubric (reason → then score)**, and we **keep the reason** so every number is inspectable. *(The production-grade suite, `mai_rag.evals`, comes in the next lab.)*
"""

# A sturdier judge — reuses `judge` + `_json` from cell 8, but prompts properly
def grade(q, answer, expected):                 # correctness, anchored + reason-first
    p = ("You are grading a RAG answer. Give a one-sentence reason, THEN a score.\n"
         "Scale: 1.0 fully correct - 0.5 partially correct or incomplete - 0.0 wrong or missing.\n"
         'Reply JSON only: {"reason": "<one sentence>", "score": <1.0|0.5|0.0>}.\n\n'
         f"QUESTION: {q}\nEXPECTED: {expected}\nANSWER: {answer}")
    return _json(judge.invoke(p).content)

def faithfulness_claims(answer, contexts):       # claim-decomposition, not holistic
    ctx = "\n\n".join(contexts)
    p = ("Break the ANSWER into its distinct factual claims. For each, decide whether the CONTEXT "
         "supports it. score = supported_claims / total_claims (use 1.0 if there are no factual "
         "claims, e.g. a refusal like 'I don't have enough information').\n"
         'Reply JSON only: {"reason": "<n claims, m supported>", "score": <0..1>}.\n\n'
         f"CONTEXT:\n{ctx}\n\nANSWER: {answer}")
    return _json(judge.invoke(p).content)

# sanity-check on the recency landmine
out = naive_rag(golden[0]["q"])
print("CORRECTNESS :", grade(golden[0]["q"], out["answer"], golden[0]["expected"]))
print("FAITHFULNESS:", faithfulness_claims(out["answer"], out["contexts"]))

# Re-score the SAME naive RAG with the sturdier judge — now every score has a reason
rows = []
for c in golden:
    out = naive_rag(c["q"])
    corr  = grade(c["q"], out["answer"], c["expected"])
    faith = faithfulness_claims(out["answer"], out["contexts"])
    rows.append({
        "question": c["q"][:38], "tag": c["tag"],
        "correctness": corr["score"],   "why_correct": corr["reason"][:55],
        "faithfulness": faith["score"], "why_faithful": faith["reason"][:55],
    })

df2 = pd.DataFrame(rows)
pd.set_option("display.max_colwidth", 60)
display(df2)
print("\nBASELINE (sturdier judge):", df2[["correctness", "faithfulness"]].mean().round(3).to_dict())
print("Compare to the home-rolled judge above — same answers, more honest (and auditable) scores.")

"""## Whose fault is it — the retriever or the generator?

End-to-end "correctness" hides *where* the pipeline broke. Split it:

- **Retrieval accuracy** — did the embeddings fetch the right doc(s)? (`recall@k`, `hit@1` vs the `support` field). Low here ⇒ **embedding / retrieval problem** — no LLM can answer from docs it never saw.
- **Completeness** — given what *was* retrieved, did the answer cover everything it should? High recall but low completeness ⇒ **generation / LLM problem**.

Cross the two and every failure gets a verdict — so you know whether Lab 2 should fix *retrieval* or *generation*.
"""

# Stage 1 — RETRIEVAL accuracy (no LLM; isolates the embeddings)
def retrieval_metrics(q, support, k=5):
    if "none" in support.lower():
        return {"recall": None, "hit@1": None}          # unanswerable: nothing to fetch
    wanted = [s.strip() for s in support.split("+")]     # multi-hop = >1 doc
    got = [h.source for h in store.search(q, k=k)]
    recall = sum(w in got for w in wanted) / len(wanted)
    hit1 = 1.0 if (got and got[0] in wanted) else 0.0
    return {"recall": recall, "hit@1": hit1}

rdf = pd.DataFrame([{"question": c["q"][:36], "tag": c["tag"], **retrieval_metrics(c["q"], c["support"])}
                    for c in golden])
display(rdf)
print("Retrieval  recall@5:", round(rdf["recall"].dropna().mean(), 3),
      "| hit@1:", round(rdf["hit@1"].dropna().mean(), 3))

# Stage 2 — COMPLETENESS given what was retrieved, then ATTRIBUTE each failure
def completeness(answer, expected):
    p = ("Does the ANSWER cover ALL the points in the EXPECTED answer? "
         "score = fraction of required points covered (1.0 all, 0.0 none). "
         'Reply JSON only: {"reason": "<covered / missing>", "score": <0..1>}.\n\n'
         f"EXPECTED: {expected}\nANSWER: {answer}")
    return _json(judge.invoke(p).content)

rows = []
for c in golden:
    out  = naive_rag(c["q"])
    rm   = retrieval_metrics(c["q"], c["support"])
    comp = completeness(out["answer"], c["expected"])["score"]
    if rm["recall"] is None:                              # unanswerable case
        declined = "enough information" in out["answer"].lower() or "don't" in out["answer"].lower()
        diag = "OK (declined)" if declined else "LLM — hallucinated instead of declining"
    elif rm["recall"] < 1.0:
        diag = "EMBEDDING — right doc(s) not retrieved"
    elif comp < 0.75:
        diag = "LLM — had the docs, answer wrong/incomplete"
    else:
        diag = "OK"
    rows.append({"question": c["q"][:32], "tag": c["tag"],
                 "recall": rm["recall"], "completeness": comp, "diagnosis": diag})

ddf = pd.DataFrame(rows)
display(ddf)
print("\nWHERE IT BREAKS:", ddf["diagnosis"].value_counts().to_dict())

"""## Afterthought — but how can we evaluate if we never read the documents?

We wrote those `expected` answers from memory and graded against them. If we never opened the source, the whole baseline is built on guesses. So: **browse the corpus, read the real policy, then go back and re-ground each `expected` in what the document actually says** (and note which doc supports it).
"""

# Function 1 — SEARCH for docs by keyword (note the id of the one you want)
import pandas as pd

def search_docs(keyword):
    return pd.read_sql(
        "SELECT id, title, source FROM documents WHERE title LIKE ? OR source LIKE ?",
        store.conn, params=(f"%{keyword}%", f"%{keyword}%"))

search_docs("leave")

# Function 2 — READ a doc by id (paste an id from search_docs above)
def read_doc(doc_id):
    d = store.conn.execute("SELECT title, source FROM documents WHERE id=?", (doc_id,)).fetchone()
    body = store.conn.execute(
        "SELECT content FROM chunks WHERE document_id=? ORDER BY chunk_index", (doc_id,)).fetchall()
    print(f"{d['title']}  ·  {d['source']}\n{'='*70}")
    print("\n".join(r["content"] for r in body))

read_doc(67)   # ← replace with an id from search_docs()